export const ALLEN_BRAIN_MAP_TITLE = 'Allen Institute for Brain Science';

export const FETCH_ERROR_MESSAGE = 'There was a problem fetching data for this page.';

export const SPECIMEN_ID_TITLE = 'Specimen ID';
export const SPECIMEN_TAXONOMY_FILTER_REFERENCE_ID = '7MZTO66W0B9663JCJ20';
export const SPECIMEN_ID_REFERENCE_ID = 'QL1JDPEMY417CMVCH4I';
export const SPECIMEN_ID_REFERENCE_ID_V2 = '75S21YZHJ1CZ585S202';
export const SPECIMEN_T_TYPE_REFERENCE_ID = 'DW0F0S320VR4NX0DBPT';
export const SPECIMEN_T_TYPE_CLASS_REFERENCE_ID = 'Z8BZR1LDP9G4I97O394';
export const SPECIMEN_T_TYPE_SUBCLASS_REFERENCE_ID = 'O267WEUPC2MMK3MI7ZY';
export const SPECIMENS_COLUMN_REF_IDS = [
    SPECIMEN_ID_REFERENCE_ID_V2,
    SPECIMEN_T_TYPE_CLASS_REFERENCE_ID,
    SPECIMEN_T_TYPE_SUBCLASS_REFERENCE_ID,
];
export const SPECIMEN_T_TYPE_REF_IDS = [
    SPECIMEN_T_TYPE_REFERENCE_ID,
    SPECIMEN_T_TYPE_CLASS_REFERENCE_ID,
    SPECIMEN_T_TYPE_SUBCLASS_REFERENCE_ID,
];

export const SORT_QUERY_DELIMITER = '~';

export const FILTER_FIELD_QUERY_DELIMITER = '.';
export const FILTER_ARGUMENT_QUERY_DELIMITER = '~';

export const QUERYSTRING_COMMA_REPLACER = '|';
export const ALIAS_PREFIX_DELIMITER = '__';
export const REF_ID_ALIAS_PREFIX = `ref_id${ALIAS_PREFIX_DELIMITER}`;

export const PROJECT_REFERENCE_IDS = 'projectReferenceIds';
